model:
  name: "Qwen/Qwen3-30B-A3B"
  max_seq_length: 2048
  per_device_batch_size: 4
  learning_rate: 1e-5
  clip_grad_norm: 1.0
  output_router_logits: true

optim:
  adam_beta1: 0.9
  adam_beta2: 0.999
  weight_decay: 0.01

config:
  device_type: "cuda"
  backend: "nccl"
  use_amp: true
  amp_dtype: bf16
  grad_accum_steps: 4
  max_steps: 500
  eval_interval: 10
  eval_steps: 10
  checkpoint_interval: 0
  checkpoint_dir: "checkpoints"
  resume_from: null

engine:
  cpu_offload: false
  activation_checkpoint: false
  checkpoint_every_n: 1
  find_unused_parameters: false  # mainly for dense vs moe
  overlap_backward_reductions: true 
  compile: false


data:
  dir: "/root/data/"

parallel:
  dp_replicate: 1
  dp_shard: 1
  tp: 1
  cp: 1
  sp: 1
  ep: 1
  expert_tp: 1
  pp: 1
